# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest

    - name: PyInstaller Linux
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with:
        # Directory containing source code & .spec file (optional requirements.txt).
        path: / # default is src
        # Specify a custom URL for PYPI
        #pypi_url: # optional, default is https://pypi.python.org/
        # Specify a custom URL for PYPI Index
        #pypi_index_url: # optional, default is https://pypi.python.org/simple
        # Specify a file path for .spec file
        #spec: # optional, default is 
        # Specify whether to install Tkinter or not
        #tkinter: # optional
